/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:d2ac2025e85c3dd00d5dec2c4f159486:457618e407a6c68d3e77190ab64ae72b:ab4ed61aee9c20e10cf08a931d1d0a05$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class UITextureAtlas
	{
		public const string BackgroundTopBar = "BackgroundTopBar";
		public const string ButtonActive = "ButtonActive";
		public const string ButtonCheckBoxActive = "ButtonCheckBoxActive";
		public const string ButtonNormal = "ButtonNormal";
		public const string ButtonPullDown = "ButtonPullDown";
		public const string ButtonSelected = "ButtonSelected";
		public const string CellActive = "CellActive";
		public const string CellNormal = "CellNormal";
		public const string CellSelected = "CellSelected";
		public const string DualSliderTrackLeft = "DualSliderTrackLeft";
		public const string DualSliderTrackMiddle = "DualSliderTrackMiddle";
		public const string IconCheck = "IconCheck";
		public const string IconMinus = "IconMinus";
		public const string IconPlus = "IconPlus";
		public const string IconPointer = "IconPointer";
		public const string IconScrollBarDown = "IconScrollBarDown";
		public const string IconScrollBarDownActive = "IconScrollBarDownActive";
		public const string IconScrollBarDownSelected = "IconScrollBarDownSelected";
		public const string IconScrollBarLeft = "IconScrollBarLeft";
		public const string IconScrollBarLeftActive = "IconScrollBarLeftActive";
		public const string IconScrollBarLeftSelected = "IconScrollBarLeftSelected";
		public const string IconScrollBarRight = "IconScrollBarRight";
		public const string IconScrollBarRightActive = "IconScrollBarRightActive";
		public const string IconScrollBarRightSelected = "IconScrollBarRightSelected";
		public const string IconScrollBarUp = "IconScrollBarUp";
		public const string IconScrollBarUpActive = "IconScrollBarUpActive";
		public const string IconScrollBarUpSelected = "IconScrollBarUpSelected";
		public const string MissingIcon = "MissingIcon";
		public const string ModalBackground = "ModalBackground";
		public const string ModalBackgroundDestructive = "ModalBackgroundDestructive";
		public const string ScrollBarBackground = "ScrollBarBackground";
		public const string ShadowBottom = "ShadowBottom";
		public const string ShadowLeftAndCorners = "ShadowLeftAndCorners";
		public const string ShadowRightAndCorners = "ShadowRightAndCorners";
		public const string ShadowTop = "ShadowTop";
		public const string SliderTrackLeft = "SliderTrackLeft";
		public const string SliderTrackRight = "SliderTrackRight";
		public const string TextFieldBackground = "TextFieldBackground";
		public const string TextFieldIBar = "TextFieldIBar";
	}
}